const VOCABULARY = [
    { word: "abandon", meaning: "버리다, 포기하다", keyword: "abandoned", pronunciation: "[əˈbændən]", example: "They had to abandon the old house." },
    { word: "ability", meaning: "능력", keyword: "skill", pronunciation: "[əˈbɪlɪti]", example: "She has the ability to speak three languages." },
    { word: "abnormal", meaning: "비정상적인", keyword: "weird", pronunciation: "[æbˈnɔːrml]", example: "The weather was abnormal for this time of year." },
    { word: "aboard", meaning: "탑승한", keyword: "airplane", pronunciation: "[əˈbɔːrd]", example: "All passengers are aboard the ship." },
    { word: "abolish", meaning: "폐지하다", keyword: "cancel", pronunciation: "[əˈbɑːlɪʃ]", example: "The government decided to abolish the tax." },
    { word: "about", meaning: "대하여, 약", keyword: "circle", pronunciation: "[əˈbaʊt]", example: "I am thinking about my future." },
    { word: "above", meaning: "~보다 위에", keyword: "cloud", pronunciation: "[əˈbʌv]", example: "The bird flew above the trees." },
    { word: "abroad", meaning: "해외로", keyword: "travel", pronunciation: "[əˈbrɔːd]", example: "She wants to study abroad next year." },
    { word: "absence", meaning: "결석, 부재", keyword: "empty", pronunciation: "[ˈæbsəns]", example: "His absence was noticed by everyone." },
    { word: "absolute", meaning: "절대적인", keyword: "king", pronunciation: "[ˈæbsəluːt]", example: "He has absolute confidence in his team." },
    { word: "absorb", meaning: "흡수하다", keyword: "sponge", pronunciation: "[əbˈsɔːrb]", example: "Plants absorb water through their roots." },
    { word: "abstract", meaning: "추상적인", keyword: "modern art", pronunciation: "[ˈæbstrækt]", example: "The artist painted an abstract picture." },
    { word: "absurd", meaning: "터무니없는", keyword: "joke", pronunciation: "[əbˈsɜːrd]", example: "That idea is completely absurd." },
    { word: "abundant", meaning: "풍부한", keyword: "harvest", pronunciation: "[əˈbʌndənt]", example: "The island has abundant natural resources." },
    { word: "abuse", meaning: "남용하다, 학대하다", keyword: "angry", pronunciation: "[əˈbjuːs]", example: "We must not abuse our power." },
    { word: "academic", meaning: "학업의", keyword: "school", pronunciation: "[ˌækəˈdemɪk]", example: "He has a strong academic background." },
    { word: "accent", meaning: "악센트, 강조", keyword: "speech", pronunciation: "[ˈæksent]", example: "She speaks English with a French accent." },
    { word: "accept", meaning: "받아들이다", keyword: "agreement", pronunciation: "[əkˈsept]", example: "He accepted the job offer." },
    { word: "access", meaning: "접근", keyword: "door", pronunciation: "[ˈækses]", example: "We need a password to access the system." },
    { word: "accident", meaning: "사고", keyword: "car crash", pronunciation: "[ˈæksɪdənt]", example: "I had a minor accident this morning." },
    { word: "accompany", meaning: "동반하다", keyword: "friends", pronunciation: "[əˈkʌmpəni]", example: "Would you like me to accompany you?" },
    { word: "accomplish", meaning: "성취하다", keyword: "trophy", pronunciation: "[əˈkɑːmplɪʃ]", example: "We accomplished our goals." },
    { word: "accord", meaning: "일치하다", keyword: "handshake", pronunciation: "[əˈkɔːrd]", example: "Their stories accord with the facts." },
    { word: "account", meaning: "계좌, 설명", keyword: "bank", pronunciation: "[əˈkaʊnt]", example: "I opened a bank account yesterday." },
    { word: "accurate", meaning: "정확한", keyword: "target", pronunciation: "[ˈækjərət]", example: "Is the information accurate?" },
    { word: "accuse", meaning: "고발하다, 비난하다", keyword: "judge", pronunciation: "[əˈkjuːz]", example: "He was accused of stealing." },
    { word: "achieve", meaning: "달성하다", keyword: "success", pronunciation: "[əˈtʃiːv]", example: "You can achieve anything if you work hard." },
    { word: "acid", meaning: "산, 산성의", keyword: "lemon", pronunciation: "[ˈæsɪd]", example: "The rain was slightly acid." },
    { word: "acknowledge", meaning: "인정하다", keyword: "nod", pronunciation: "[əkˈnɑːlɪdʒ]", example: "He acknowledged his mistake." },
    { word: "acquire", meaning: "습득하다", keyword: "book", pronunciation: "[əˈkwaɪər]", example: "She acquired a new skill." },
    { word: "across", meaning: "가로질러", keyword: "bridge", pronunciation: "[əˈkrɔːs]", example: "They walked across the street." },
    { word: "act", meaning: "행동하다", keyword: "theater", pronunciation: "[ækt]", example: "Think before you act." },
    { word: "action", meaning: "행동", keyword: "running", pronunciation: "[ˈækʃn]", example: "Actions speak louder than words." },
    { word: "active", meaning: "활동적인", keyword: "energy", pronunciation: "[ˈæktɪv]", example: "She is very active in sports." },
    { word: "activity", meaning: "활동", keyword: "sports", pronunciation: "[ækˈtɪvəti]", example: "There are many activities for students." },
    { word: "actor", meaning: "배우", keyword: "movie star", pronunciation: "[ˈæktər]", example: "He is a famous actor." },
    { word: "actual", meaning: "실제의", keyword: "truth", pronunciation: "[ˈæktʃuəl]", example: "The actual cost was higher than expected." },
    { word: "adapt", meaning: "적응하다", keyword: "chameleon", pronunciation: "[əˈdæpt]", example: "Animals adapt to their environment." },
    { word: "add", meaning: "더하다", keyword: "plus", pronunciation: "[æd]", example: "If you add 2 and 2, you get 4." },
    { word: "addict", meaning: "중독시키다", keyword: "computer game", pronunciation: "[ˈædɪkt]", example: "He is addicted to coffee." },
    { word: "addition", meaning: "추가", keyword: "stack", pronunciation: "[əˈdɪʃn]", example: "The new room is a great addition to the house." },
    { word: "address", meaning: "주소, 연설하다", keyword: "envelope", pronunciation: "[əˈdres]", example: "What is your email address?" },
    { word: "adequate", meaning: "적당한", keyword: "enough", pronunciation: "[ˈædɪkwət]", example: "The food was adequate for everyone." },
    { word: "adjust", meaning: "조절하다", keyword: "dial", pronunciation: "[əˈdʒʌst]", example: "You can adjust the volume." },
    { word: "admire", meaning: "존경하다", keyword: "respect", pronunciation: "[ədˈmaɪər]", example: "I admire her courage." },
    { word: "admit", meaning: "인정하다", keyword: "confess", pronunciation: "[ədˈmɪt]", example: "He admitted that he was wrong." },
    { word: "adopt", meaning: "채택하다, 입양하다", keyword: "family", pronunciation: "[əˈdɑːpt]", example: "They decided to adopt a child." },
    { word: "adult", meaning: "성인", keyword: "man", pronunciation: "[əˈdʌlt]", example: "Only adults can enter the club." },
    { word: "advance", meaning: "진보하다", keyword: "forward", pronunciation: "[ədˈvæns]", example: "Technology is advancing rapidly." },
    { word: "advantage", meaning: "이점", keyword: "winning", pronunciation: "[ədˈvæntɪdʒ]", example: "The high position gave them an advantage." },
    { word: "adventure", meaning: "모험", keyword: "mountain", pronunciation: "[ədˈventʃər]", example: "They went on a mountain adventure." },
    { word: "advertise", meaning: "광고하다", keyword: "billing", pronunciation: "[ˈædvərtaɪz]", example: "The company advertised its new product." },
    { word: "advice", meaning: "조언", keyword: "talk", pronunciation: "[ədˈvaɪs]", example: "Can you give me some advice?" },
    { word: "advise", meaning: "상담하다, 조언하다", keyword: "doctor", pronunciation: "[ədˈvaɪz]", example: "The doctor advised me to rest." },
    { word: "advocate", meaning: "옹호하다", keyword: "shout", pronunciation: "[ˈædvəkət]", example: "She is a strong advocate for education." },
    { word: "affair", meaning: "사건, 일", keyword: "business", pronunciation: "[əˈfer]", example: "The minister handled the affair professionally." },
    { word: "affect", meaning: "영향을 미치다", keyword: "wave", pronunciation: "[əˈfekt]", example: "Pollution affects the environment." },
    { word: "afford", meaning: "여유가 되다", keyword: "money", pronunciation: "[əˈfɔːrd]", example: "I can't afford to buy a new car." },
    { word: "afraid", meaning: "두려워하는", keyword: "ghost", pronunciation: "[əˈfreɪd]", example: "Don't be afraid of the dark." },
    { word: "after", meaning: "후에", keyword: "clock", pronunciation: "[ˈæftər]", example: "See you after school." },
    { word: "afternoon", meaning: "오후", keyword: "sunset", pronunciation: "[ˌæftərˈnuːn]", example: "Let's meet tomorrow afternoon." },
    { word: "again", meaning: "다시", keyword: "repeat", pronunciation: "[əˈɡen]", example: "Could you repeat that again?" },
    { word: "against", meaning: "대항하여", keyword: "fight", pronunciation: "[əˈɡenst]", example: "They played against a strong team." },
    { word: "age", meaning: "나이, 시대", keyword: "old", pronunciation: "[eɪdʒ]", example: "What is your age?" },
    { word: "agency", meaning: "대리점, 기관", keyword: "office", pronunciation: "[ˈeɪdʒənsi]", example: "The travel agency booked our flights." },
    { word: "agenda", meaning: "안건", keyword: "list", pronunciation: "[əˈdʒendə]", example: "Let's look at the agenda for the meeting." },
    { word: "agent", meaning: "대리인", keyword: "spy", pronunciation: "[ˈeɪdʒənt]", example: "He works as a real estate agent." },
    { word: "aggressive", meaning: "공격적인", keyword: "lion", pronunciation: "[əˈɡresɪv]", example: "The dog showed aggressive behavior." },
    { word: "ago", meaning: "전", keyword: "history", pronunciation: "[əˈɡəʊ]", example: "I finished the work two hours ago." },
    { word: "agree", meaning: "동의하다", keyword: "shake hands", pronunciation: "[əˈɡriː]", example: "I agree with your suggestion." },
    { word: "agriculture", meaning: "농업", keyword: "farm", pronunciation: "[ˈæɡrɪkʌltʃər]", example: "Agriculture is important for the economy." },
    { word: "ahead", meaning: "앞에", keyword: "road", pronunciation: "[əˈhed]", example: "The road ahead is clear." },
    { word: "aid", meaning: "원조, 돕다", keyword: "help", pronunciation: "[eɪd]", example: "They sent aid to the victims." },
    { word: "aim", meaning: "목표, 겨냥하다", keyword: "arrow", pronunciation: "[eɪm]", example: "My aim is to become a doctor." },
    { word: "air", meaning: "공기", keyword: "blue sky", pronunciation: "[er]", example: "Open the window for some fresh air." },
    { word: "aircraft", meaning: "항공기", keyword: "plane", pronunciation: "[ˈerkræft]", example: "The aircraft took off on time." },
    { word: "airport", meaning: "공항", keyword: "traveler", pronunciation: "[ˈerpɔːrt]", example: "I will meet you at the airport." },
    { word: "alarm", meaning: "경보", keyword: "bell", pronunciation: "[əˈlɑːrm]", example: "The fire alarm went off." },
    { word: "alcohol", meaning: "알코올", keyword: "drink", pronunciation: "[ˈælkəhɔːl]", example: "Alcohol can be harmful to health." },
    { word: "alert", meaning: "경계하는", keyword: "warning", pronunciation: "[əˈlɜːrt]", example: "Be alert for any changes." },
    { word: "alike", meaning: "비슷한", keyword: "twins", pronunciation: "[əˈlaɪk]", example: "The two sisters look alike." },
    { word: "alive", meaning: "살아있는", keyword: "heart", pronunciation: "[əˈlaɪv]", example: "It's good to be alive." },
    { word: "all", meaning: "모든", keyword: "earth", pronunciation: "[ɔːl]", example: "All the students were present." },
    { word: "allot", meaning: "할당하다", keyword: "pizza", pronunciation: "[əˈlɑːt]", example: "The teacher allotted time for discussion." },
    { word: "allow", meaning: "허락하다", keyword: "key", pronunciation: "[əˈlaʊ]", example: "Smoking is not allowed here." },
    { word: "almost", meaning: "거의", keyword: "near", pronunciation: "[ˈɔːlməʊst]", example: "I am almost finished." },
    { word: "alone", meaning: "혼자", keyword: "island", pronunciation: "[əˈləʊn]", example: "She lives alone in the house." },
    { word: "along", meaning: "따라서", keyword: "walking", pronunciation: "[əˈlɔːŋ]", example: "They walked along the river." },
    { word: "aloud", meaning: "소리 내어", keyword: "speaker", pronunciation: "[əˈlaʊd]", example: "Read the poem aloud." },
    { word: "alphabet", meaning: "알파벳", keyword: "abc", pronunciation: "[ˈælfəbet]", example: "Children learn the alphabet in school." },
    { word: "already", meaning: "이미", keyword: "done", pronunciation: "[ɔːlˈredi]", example: "I have already finished my homework." },
    { word: "also", meaning: "또한", keyword: "plus", pronunciation: "[ˈɔːlsəʊ]", example: "She is also a talented singer." },
    { word: "alter", meaning: "바꾸다, 변경하다", keyword: "change", pronunciation: "[ˈɔːltər]", example: "He had to alter his plans." },
    { word: "alternative", meaning: "대안", keyword: "choice", pronunciation: "[ɔːlˈtɜːrnətɪv]", example: "Is there an alternative way?" },
    { word: "although", meaning: "비록 ~일지라도", keyword: "rain", pronunciation: "[ɔːlˈðəʊ]", example: "Although it was raining, they went out." },
    { word: "altogether", meaning: "완전히, 아주", keyword: "together", pronunciation: "[ˌɔːltəˈɡeðər]", example: "The situation changed altogether." },
    { word: "always", meaning: "항상", keyword: "infinity", pronunciation: "[ˈɔːlweɪz]", example: "I always wake up at 7 AM." },
    { word: "amaze", meaning: "놀라게 하다", keyword: "magic", pronunciation: "[əˈmeɪz]", example: "The view amazed us." },
    { word: "ambassador", meaning: "대사", keyword: "flag", pronunciation: "[æmˈbæsədər]", example: "He was appointed as the ambassador." },
    { word: "ambition", meaning: "야망", keyword: "ladder", pronunciation: "[æmˈbɪʃn]", example: "She has the ambition to become CEO." },
    { word: "bible", meaning: "성경", keyword: "book", pronunciation: "[ˈbaɪbl]", example: "He reads the Bible every day." },
    { word: "church", meaning: "교회", keyword: "church", pronunciation: "[tʃɜːrtʃ]", example: "They go to church on Sundays." },
    { word: "grace", meaning: "은혜", keyword: "angel", pronunciation: "[ɡreɪs]", example: "The dancer moved with grace." },
    { word: "pioneer", meaning: "개척자", keyword: "explorer", pronunciation: "[ˌpaɪəˈnɪr]", example: "She was a pioneer in science." },
    { word: "mountain", meaning: "산", keyword: "mountain", pronunciation: "[ˈmaʊntn]", example: "The mountain peak was covered in snow." },
    { word: "river", meaning: "강", keyword: "river", pronunciation: "[ˈrɪvər]", example: "The river flows into the sea." },
    { word: "ocean", meaning: "바다", keyword: "ocean", pronunciation: "[ˈəʊʃn]", example: "The ocean is vast and deep." },
    { word: "forest", meaning: "숲", keyword: "forest", pronunciation: "[ˈfɔːrɪst]", example: "Many animals live in the forest." },
    { word: "garden", meaning: "정원", keyword: "garden", pronunciation: "[ˈɡɑːrdn]", example: "The garden is full of flowers." },
    { word: "flower", meaning: "꽃", keyword: "flower", pronunciation: "[ˈflaʊər]", example: "The flower smelled sweet." },
    { word: "animal", meaning: "동물", keyword: "animal", pronunciation: "[ˈænɪml]", example: "A dog is a loyal animal." },
    { word: "bird", meaning: "새", keyword: "bird", pronunciation: "[bɜːrd]", example: "The bird flew across the sky." },
    { word: "fish", meaning: "물고기", keyword: "fish", pronunciation: "[fɪʃ]", example: "There are many fish in the lake." },
    { word: "insect", meaning: "곤충", keyword: "insect", pronunciation: "[ˈɪnsekt]", example: "An ant is a small insect." },
    { word: "human", meaning: "인간", keyword: "people", pronunciation: "[ˈhjuːmən]", example: "Communication is essential for humans." },
    { word: "friend", meaning: "친구", keyword: "friends", pronunciation: "[frend]", example: "He is my best friend." },
    { word: "family", meaning: "가족", keyword: "family", pronunciation: "[ˈfæməli]", example: "I love spending time with my family." },
    { word: "house", meaning: "집", keyword: "house", pronunciation: "[haʊs]", example: "The house was built in 1990." },
    { word: "room", meaning: "방", keyword: "room", pronunciation: "[ruːm]", example: "The room was bright and airy." },
    { word: "school", meaning: "학교", keyword: "school", pronunciation: "[skuːl]", example: "Students learn many things at school." },
    { word: "book", meaning: "책", keyword: "book", pronunciation: "[bʊk]", example: "I read a book last week." },
    { word: "pencil", meaning: "연필", keyword: "pencil", pronunciation: "[ˈpensl]", example: "Can I borrow your pencil?" },
    { word: "paper", meaning: "종이", keyword: "paper", pronunciation: "[ˈpeɪpər]", example: "Write your name on the paper." },
    { word: "desktop", meaning: "컴퓨터", keyword: "computer", pronunciation: "[ˈdesktɑːp]", example: "I use my desktop computer for work." },
    { word: "phone", meaning: "전화", keyword: "phone", pronunciation: "[fəʊn]", example: "The phone rang three times." },
    { word: "internet", meaning: "인터넷", keyword: "web", pronunciation: "[ˈɪntərnet]", example: "The internet changed the world." },
    { word: "world", meaning: "세계", keyword: "earth", pronunciation: "[wɜːrld]", example: "Let's explore the world together." },
    { word: "nation", meaning: "국가", keyword: "flag", pronunciation: "[ˈneɪʃn]", example: "The nation celebrated its independence." },
    { word: "city", meaning: "도시", keyword: "city", pronunciation: "[ˈsɪti]", example: "Seoul is a very busy city." },
    { word: "village", meaning: "마을", keyword: "village", pronunciation: "[ˈvɪlɪdʒ]", example: "They lived in a small village." },
    { word: "street", meaning: "거리", keyword: "street", pronunciation: "[striːt]", example: "The street was crowded with people." },
    { word: "car", meaning: "자동차", keyword: "car", pronunciation: "[kɑːr]", example: "He drove his car to work." },
    { word: "bus", meaning: "버스", keyword: "bus", pronunciation: "[bʌs]", example: "The bus stops here every 30 minutes." },
    { word: "train", meaning: "기차", keyword: "train", pronunciation: "[treɪn]", example: "The train arrived at the station." },
    { word: "plane", meaning: "비행기", keyword: "plane", pronunciation: "[pleɪn]", example: "The plane flew over the mountains." },
    { word: "bicycle", meaning: "자전거", keyword: "bicycle", pronunciation: "[ˈbaɪsɪkl]", example: "Riding a bicycle is good exercise." },
    { word: "food", meaning: "음식", keyword: "food", pronunciation: "[fuːd]", example: "She prepared delicious food for us." },
    { word: "water", meaning: "물", keyword: "water", pronunciation: "[ˈwɔːtər]", example: "Drink plenty of water." },
    { word: "fruit", meaning: "과일", keyword: "fruit", pronunciation: "[fruːt]", example: "Apples are my favorite fruit." },
    { word: "vegetable", meaning: "채소", keyword: "vegetable", pronunciation: "[ˈvedʒtəbl]", example: "Eating vegetables is healthy." },
    { word: "meat", meaning: "고기", keyword: "meat", pronunciation: "[miːt]", example: "The meat was grilled to perfection." },
    { word: "bread", meaning: "빵", keyword: "bread", pronunciation: "[bred]", example: "Freshly baked bread smells great." },
    { word: "milk", meaning: "우유", keyword: "milk", pronunciation: "[mɪlk]", example: "Milk provides essential nutrients." },
    { word: "coffee", meaning: "커피", keyword: "coffee", pronunciation: "[ˈkɔːfi]", example: "I drink coffee every morning." },
    { word: "tea", meaning: "차", keyword: "tea", pronunciation: "[tiː]", example: "Would you like a cup of tea?" },
    { word: "sugar", meaning: "설탕", keyword: "sugar", pronunciation: "[ˈʃʊɡər]", example: "Don't add too much sugar to your tea." },
    { word: "salt", meaning: "소금", keyword: "salt", pronunciation: "[sɔːlt]", example: "Pass me the salt, please." },
    { word: "time", meaning: "시간", keyword: "clock", pronunciation: "[taɪm]", example: "Time passes quickly." },
    { word: "day", meaning: "낮, 하루", keyword: "sun", pronunciation: "[deɪ]", example: "It was a sunny day." },
    { word: "night", meaning: "밤", keyword: "night", pronunciation: "[naɪt]", example: "The moon shines at night." },
    { word: "month", meaning: "달", keyword: "calendar", pronunciation: "[mʌnθ]", example: "Next month is my birthday." },
    { word: "year", meaning: "해", keyword: "calendar", pronunciation: "[jɪr]", example: "They got married last year." },
    { word: "spring", meaning: "봄", keyword: "spring", pronunciation: "[sprɪŋ]", example: "Flowers bloom in spring." },
    { word: "summer", meaning: "여름", keyword: "summer", pronunciation: "[ˈsʌmər]", example: "We go swimming in summer." },
    { word: "autumn", meaning: "가을", keyword: "autumn", pronunciation: "[ˈɔːtəm]", example: "The leaves fall in autumn." },
    { word: "winter", meaning: "겨울", keyword: "winter", pronunciation: "[ˈwɪntər]", example: "It snows in winter." },
    { word: "weather", meaning: "날씨", keyword: "weather", pronunciation: "[ˈweðər]", example: "The weather is perfect for a picnic." },
    { word: "rain", meaning: "비", keyword: "rain", pronunciation: "[reɪn]", example: "I love the sound of rain." },
    { word: "snow", meaning: "눈", keyword: "snow", pronunciation: "[snəʊ]", example: "The children made a snowman." },
    { word: "wind", meaning: "바람", keyword: "wind", pronunciation: "[wɪnd]", example: "The wind blew the leaves away." },
    { word: "storm", meaning: "폭풍", keyword: "storm", pronunciation: "[stɔːrm]", example: "The storm caused many power outages." },
    { word: "cloud", meaning: "구름", keyword: "cloud", pronunciation: "[klaʊd]", example: "There was a single cloud in the sky." },
    { word: "sky", meaning: "하늘", keyword: "sky", pronunciation: "[skaɪ]", example: "The sky was a deep blue." },
    { word: "sun", meaning: "태양", keyword: "sun", pronunciation: "[sʌn]", example: "The sun rose early this morning." },
    { word: "moon", meaning: "달", keyword: "moon", pronunciation: "[muːn]", example: "The full moon was beautiful." },
    { word: "star", meaning: "별", keyword: "star", pronunciation: "[stɑːr]", example: "The night sky was filled with stars." },
    { word: "color", meaning: "색깔", keyword: "colors", pronunciation: "[ˈkʌlər]", example: "Blue is my favorite color." },
    { word: "red", meaning: "빨간색", keyword: "red", pronunciation: "[red]", example: "The red rose was stunning." },
    { word: "blue", meaning: "파란색", keyword: "blue", pronunciation: "[bluː]", example: "The sky is blue." },
    { word: "green", meaning: "초록색", keyword: "green", pronunciation: "[ɡriːn]", example: "The grass is green." },
    { word: "yellow", meaning: "노란색", keyword: "yellow", pronunciation: "[ˈjeləʊ]", example: "The sunflower is yellow." },
    { word: "black", meaning: "검정색", keyword: "black", pronunciation: "[blæk]", example: "She wore a black dress." },
    { word: "white", meaning: "하얀색", keyword: "white", pronunciation: "[waɪt]", example: "The snow was pure white." },
    { word: "body", meaning: "몸", keyword: "body", pronunciation: "[ˈbɑːdi]", example: "Exercise is good for your body." },
    { word: "head", meaning: "머리", keyword: "head", pronunciation: "[hed]", example: "He wore a hat on his head." },
    { word: "eye", meaning: "눈", keyword: "eye", pronunciation: "[aɪ]", example: "She has beautiful blue eyes." },
    { word: "ear", meaning: "귀", keyword: "ear", pronunciation: "[ɪr]", example: "The elephant has large ears." },
    { word: "nose", meaning: "코", keyword: "nose", pronunciation: "[nəʊz]", example: "The smell reached her nose." },
    { word: "mouth", meaning: "입", keyword: "mouth", pronunciation: "[maʊθ]", example: "Open your mouth wide." },
    { word: "hand", meaning: "손", keyword: "hand", pronunciation: "[hænd]", example: "Wash your hands before eating." },
    { word: "foot", meaning: "발", keyword: "foot", pronunciation: "[fʊt]", example: "He hurt his foot playing soccer." },
    { word: "heart", meaning: "심장", keyword: "heart", pronunciation: "[hɑːrt]", example: "Exercise keeps your heart healthy." },
    { word: "mind", meaning: "마음", keyword: "brain", pronunciation: "[maɪnd]", example: "Keep an open mind." },
    { word: "health", meaning: "건강", keyword: "health", pronunciation: "[helθ]", example: "Health is wealth." },
    { word: "doctor", meaning: "의사", keyword: "doctor", pronunciation: "[ˈdɑːktər]", example: "The doctor examined the patient." },
    { word: "nurse", meaning: "간호사", keyword: "nurse", pronunciation: "[nɜːrs]", example: "The nurse was very kind." },
    { word: "hospital", meaning: "병원", keyword: "hospital", pronunciation: "[ˈhɑːspɪtl]", example: "He was taken to the hospital." },
    { word: "medicine", meaning: "약", keyword: "medicine", pronunciation: "[ˈmedsn]", example: "Take your medicine on time." },
    { word: "money", meaning: "돈", keyword: "money", pronunciation: "[ˈmʌni]", example: "Money can't buy happiness." },
    { word: "market", meaning: "시장", keyword: "market", pronunciation: "[ˈmɑːrkɪt]", example: "We bought fresh fruit at the market." },
    { word: "shop", meaning: "가게", keyword: "shop", pronunciation: "[ʃɑːp]", example: "I like that coffee shop." },
    { word: "price", meaning: "가격", keyword: "price tag", pronunciation: "[praɪs]", example: "The price was very reasonable." },
    { word: "buy", meaning: "사다", keyword: "buy", pronunciation: "[baɪ]", example: "I want to buy a new laptop." },
    { word: "sell", meaning: "팔다", keyword: "sell", pronunciation: "[sel]", example: "He sells cars for a living." },
    { word: "work", meaning: "일하다", keyword: "work", pronunciation: "[wɜːrk]", example: "I have a lot of work to do." },
    { word: "job", meaning: "직업", keyword: "job", pronunciation: "[dʒɑːb]", example: "He got a new job recently." },
    { word: "office", meaning: "사무실", keyword: "office", pronunciation: "[ˈɔːfɪs]", example: "The office is on the third floor." },
    { word: "company", meaning: "회사", keyword: "company", pronunciation: "[ˈkʌmpəni]", example: "The company was founded in 1950." },
    { word: "business", meaning: "사업", keyword: "business", pronunciation: "[ˈbɪznəs]", example: "Business is booming." },
    { word: "game", meaning: "게임", keyword: "game", pronunciation: "[ɡeɪm]", example: "Let's play a game." },
    { word: "music", meaning: "음악", keyword: "music", pronunciation: "[ˈmjuːzɪk]", example: "I love listening to music." },
    { word: "movie", meaning: "영화", keyword: "movie", pronunciation: "[ˈmuːvi]", example: "They watched a movie together." },
    { word: "sport", meaning: "스포츠", keyword: "sport", pronunciation: "[spɔːrt]", example: "What is your favorite sport?" },
    { word: "soccer", meaning: "축구", keyword: "soccer", pronunciation: "[ˈsɑːkər]", example: "Soccer is a popular sport." },
    { word: "baseball", meaning: "야구", keyword: "baseball", pronunciation: "[ˈbeɪsbɔːl]", example: "He plays baseball professionally." },
    { word: "dance", meaning: "춤추다", keyword: "dance", pronunciation: "[dæns]", example: "She learned to dance ballet." },
    { word: "sing", meaning: "노래하다", keyword: "sing", pronunciation: "[sɪŋ]", example: "They sang a beautiful song." },
    { word: "read", meaning: "읽다", keyword: "read", pronunciation: "[riːd]", example: "Read the book carefully." },
    { word: "write", meaning: "쓰다", keyword: "write", pronunciation: "[raɪt]", example: "Write your name clearly." },
    { word: "speak", meaning: "말하다", keyword: "speak", pronunciation: "[spiːk]", example: "He speaks three languages fluently." },
    { word: "listen", meaning: "듣다", keyword: "listen", pronunciation: "[ˈlɪsn]", example: "Listen to the instructions." },
    { word: "learn", meaning: "배우다", keyword: "learn", pronunciation: "[lɜːrn]", example: "She learned to play the piano." },
    { word: "think", meaning: "생각하다", keyword: "think", pronunciation: "[θɪŋk]", example: "I need some time to think." },
    { word: "happy", meaning: "행복한", keyword: "happy", pronunciation: "[ˈhæpi]", example: "They were happy with the results." },
    { word: "sad", meaning: "슬픈", keyword: "sad", pronunciation: "[sæd]", example: "The news made her sad." },
    { word: "angry", meaning: "화난", keyword: "angry", pronunciation: "[ˈæŋɡri]", example: "He was angry about the delay." },
    { word: "tired", meaning: "피곤한", keyword: "tired", pronunciation: "[ˈtaɪərd]", example: "I am tired after the long day." },
    { word: "brave", meaning: "용감한", keyword: "brave", pronunciation: "[breɪv]", example: "He was a brave soldier." },
    { word: "clever", meaning: "영리한", keyword: "clever", pronunciation: "[ˈklevər]", example: "That was a clever idea." },
    { word: "beautiful", meaning: "아름다운", keyword: "beautiful", pronunciation: "[ˈbjuːtɪfl]", example: "The sunset was beautiful." },
    { word: "strong", meaning: "강한", keyword: "strong", pronunciation: "[strɔːŋ]", example: "He is a strong athlete." },
    { word: "weak", meaning: "약한", keyword: "weak", pronunciation: "[wiːk]", example: "The signal was very weak." },
    { word: "hot", meaning: "더운", keyword: "hot", pronunciation: "[hɑːt]", example: "It was a hot summer day." },
    { word: "cold", meaning: "추운", keyword: "cold", pronunciation: "[kəʊld]", example: "Wear a coat, it's cold outside." },
    { word: "big", meaning: "큰", keyword: "big", pronunciation: "[bɪɡ]", example: "The elephant is a big animal." },
    { word: "small", meaning: "작은", keyword: "small", pronunciation: "[smɔːl]", example: "The mouse is a small animal." },
    { word: "new", meaning: "새로운", keyword: "new", pronunciation: "[nuː]", example: "I bought a new phone." },
    { word: "old", meaning: "오래된", keyword: "old", pronunciation: "[əʊld]", example: "The old building was torn down." },
    { word: "fast", meaning: "빠른", keyword: "fast", pronunciation: "[fæst]", example: "He ran fast to catch the bus." },
    { word: "slow", meaning: "느린", keyword: "slow", pronunciation: "[sləʊ]", example: "The turtle is very slow." },
    { word: "true", meaning: "참된", keyword: "true", pronunciation: "[truː]", example: "Is it true that you're leaving?" },
    { word: "false", meaning: "거짓의", keyword: "false", pronunciation: "[fɔːls]", example: "The statement was false." },
    { word: "zebra", meaning: "얼룩말", keyword: "zebra", pronunciation: "[ˈziːbrə]", example: "The zebra has black and white stripes." }
];
